// <auto-generated />
using System;
using CarMaintenanceTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarMaintenanceTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218014127_AddTrackChangeEntity")]
    partial class AddTrackChangeEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentKm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.CarMaintenanceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalculatedNextDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CalculatedNextKm")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("IntervalType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastServiceKm")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("MaintenanceTemplateId");

                    b.ToTable("CarMaintenanceItems", (string)null);
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.MaintenanceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IntervalType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTemplates", (string)null);
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.TrackChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarMaintenanceItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarMaintenanceItemId");

                    b.ToTable("TrackChanges", (string)null);
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.CarMaintenanceItem", b =>
                {
                    b.HasOne("CarMaintenanceTracker.Api.Entities.Car", "Car")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMaintenanceTracker.Api.Entities.MaintenanceTemplate", "MaintenanceTemplate")
                        .WithMany()
                        .HasForeignKey("MaintenanceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("MaintenanceTemplate");
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.TrackChange", b =>
                {
                    b.HasOne("CarMaintenanceTracker.Api.Entities.CarMaintenanceItem", "CarMaintenanceItem")
                        .WithMany()
                        .HasForeignKey("CarMaintenanceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarMaintenanceItem");
                });

            modelBuilder.Entity("CarMaintenanceTracker.Api.Entities.Car", b =>
                {
                    b.Navigation("MaintenanceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
